version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file LambdaCDDemo/samTemplate.yaml --s3-bucket s3bucketsrikanth --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
